name: Compile Typst Paper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Fontist
        uses: fontist/setup-fontist@v2
      - name: Install Source Sans Pro font
        run: fontist install "Source Sans Pro"
      - uses: typst-community/setup-typst@v4
      - name: Set output filename
        id: vars
        run: |
          month_letter=$(date +'%b' | tr '[:upper:]' '[:lower:]')
          year_short=$(date +'%y')
          filename="cv_hugo_folcher_${month_letter}_${year_short}.pdf"
          echo "output_name=$filename" >> $GITHUB_OUTPUT
      - name: Compile Typst file
        run: typst compile generate.typ "${{ steps.vars.outputs.output_name }}"
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: "${{ steps.vars.outputs.output_name }}"
