name: Compile and Publish Typst PDF

on:
  push:
    branches:
      - main  # or your target branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Fontist
        uses: fontist/setup-fontist@v2

      - name: Install Source Sans Pro font
        run: fontist install "Source Sans Pro"

      - uses: typst-community/setup-typst@v4

      - name: Set output filename
        id: vars
        run: |
          month_letter=$(date +'%b' | tr '[:upper:]' '[:lower:]')
          year_short=$(date +'%y')
          filename="cv_hugo_folcher_${month_letter}_${year_short}.pdf"
          echo "output_name=$filename" >> $GITHUB_OUTPUT

      - name: Compile Typst file
        run: |
          mkdir -p output
          typst compile generate.typ "output/${{ steps.vars.outputs.output_name }}" --font-path ~/.fontist/fonts

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          enable_jekyll: false
