name: Compile and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: typst-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Fontist
        uses: fontist/setup-fontist@v2

      - name: Install Source Sans Pro font
        run: fontist install "Source Sans Pro"

      - uses: typst-community/setup-typst@v4

      - name: Set output filename
        id: vars
        run: |
          month_letter=$(date +'%b' | tr '[:upper:]' '[:lower:]')
          year_short=$(date +'%y')
          filename="cv_hugo_folcher_${month_letter}_${year_short}.pdf"
          echo "output_name=$filename" >> $GITHUB_OUTPUT

      - name: Compile Typst file
        run: |
          mkdir -p output
          typst compile generate.typ "output/${{ steps.vars.outputs.output_name }}" --font-path ~/.fontist/fonts

      - name: Update README with latest PDF link
        run: |
          filename=${{ steps.vars.outputs.output_name }}
          # Use sed to replace the existing PDF link with the new filename in README.md
          sed -i -E "s|(https://github.com/hufolcher/cv/blob/publish/)[^ )]+\.pdf|\1${filename}|g" README.md

      - name: Commit and push README update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README with latest PDF link"
          git push origin main


